#!/usr/bin/python
import Adafruit_DHT
import sys

sensor = Adafruit_DHT.DHT22
pin = 4


if len(sys.argv) == 2 and sys.argv[1] == 'config':
	print """graph_title Humidity
graph_vlabel %
graph_category dht22
humidity.label humidity
humidity.min 0.0
humidity.max 100.0
humidity.warning 55
humidity.critical 60
"""
	sys.exit(0);


# Try to grab a sensor reading.  Use the read_retry method which will retry up
# to 15 times to get a sensor reading (waiting 2 seconds between each retry).
humidity, temperature = Adafruit_DHT.read_retry(sensor, pin)

if humidity is not None and temperature is not None:
	print 'humidity.value %0.1f' % (humidity)
else:
	print 'Failed to get reading. Try again!'
	sys.exit(-1);
